# This is the configuration used to check the rubocop source code.
inherit_from: .rubocop_todo.yml

require:
  - rubocop/cop/internal_affairs
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false


Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*


Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HeredocIndentation:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'


RSpec/PredicateMatcher:
  EnforcedStyle: explicit

RSpec/NestedGroups:
  Max: 7
